name: Linting 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        working-directory: ./frontend
        run: npm install
      - name: Run ESLint for frontend
        working-directory: ./frontend
        run: npm run lint
