name: Deployment test 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install modules for frontend
        working-directory: ./frontend
        run: npm install
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      - name: Start backend server
        working-directory: ./backend
        run: node --experimental-json-modules index.js
